//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class topic {
    
    private title titleField;
    
    private shortdesc shortdescField;
    
    private prolog prologField;
    
    private body bodyField;
    
    private string idField;
    
    private string outputclassField;
    
    private string cmsIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public title title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public shortdesc shortdesc {
        get {
            return this.shortdescField;
        }
        set {
            this.shortdescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public prolog prolog {
        get {
            return this.prologField;
        }
        set {
            this.prologField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public body body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string outputclass {
        get {
            return this.outputclassField;
        }
        set {
            this.outputclassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cmsId {
        get {
            return this.cmsIdField;
        }
        set {
            this.cmsIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class title {
    
    private i[] iField;
    
    private b bField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("i", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public i[] i {
        get {
            return this.iField;
        }
        set {
            this.iField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public b b {
        get {
            return this.bField;
        }
        set {
            this.bField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class i {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class note {
    
    private u[] uField;
    
    private string idField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("u", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public u[] u {
        get {
            return this.uField;
        }
        set {
            this.uField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class u {
    
    private b bField;
    
    private i iField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public b b {
        get {
            return this.bField;
        }
        set {
            this.bField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public i i {
        get {
            return this.iField;
        }
        set {
            this.iField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class b {
    
    private i iField;
    
    private sub subField;
    
    private sup supField;
    
    private u uField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public i i {
        get {
            return this.iField;
        }
        set {
            this.iField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public sub sub {
        get {
            return this.subField;
        }
        set {
            this.subField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public sup sup {
        get {
            return this.supField;
        }
        set {
            this.supField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public u u {
        get {
            return this.uField;
        }
        set {
            this.uField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sub {
    
    private b bField;
    
    private i iField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public b b {
        get {
            return this.bField;
        }
        set {
            this.bField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public i i {
        get {
            return this.iField;
        }
        set {
            this.iField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sup {
    
    private i iField;
    
    private b bField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public i i {
        get {
            return this.iField;
        }
        set {
            this.iField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public b b {
        get {
            return this.bField;
        }
        set {
            this.bField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ul {
    
    private li[] liField;
    
    private string outputclassField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("li", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public li[] li {
        get {
            return this.liField;
        }
        set {
            this.liField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string outputclass {
        get {
            return this.outputclassField;
        }
        set {
            this.outputclassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class li {
    
    private ol[] olField;
    
    private b[] bField;
    
    private p[] pField;
    
    private i[] iField;
    
    private sup[] supField;
    
    private u[] uField;
    
    private fn fnField;
    
    private fig[] figField;
    
    private sub[] subField;
    
    private ul[] ulField;
    
    private foreign foreignField;
    
    private xref xrefField;
    
    private image[] imageField;
    
    private note[] noteField;
    
    private string outputclassField;
    
    private string propsField;
    
    private string idField;
    
    private string otherpropsField;
    
    private string dField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ol", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ol[] ol {
        get {
            return this.olField;
        }
        set {
            this.olField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("b", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public b[] b {
        get {
            return this.bField;
        }
        set {
            this.bField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("p", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public p[] p {
        get {
            return this.pField;
        }
        set {
            this.pField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("i", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public i[] i {
        get {
            return this.iField;
        }
        set {
            this.iField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public sup[] sup {
        get {
            return this.supField;
        }
        set {
            this.supField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("u", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public u[] u {
        get {
            return this.uField;
        }
        set {
            this.uField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public fn fn {
        get {
            return this.fnField;
        }
        set {
            this.fnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("fig", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public fig[] fig {
        get {
            return this.figField;
        }
        set {
            this.figField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sub", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public sub[] sub {
        get {
            return this.subField;
        }
        set {
            this.subField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ul", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ul[] ul {
        get {
            return this.ulField;
        }
        set {
            this.ulField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public foreign foreign {
        get {
            return this.foreignField;
        }
        set {
            this.foreignField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public xref xref {
        get {
            return this.xrefField;
        }
        set {
            this.xrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("image", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public image[] image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("note", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public note[] note {
        get {
            return this.noteField;
        }
        set {
            this.noteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string outputclass {
        get {
            return this.outputclassField;
        }
        set {
            this.outputclassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string props {
        get {
            return this.propsField;
        }
        set {
            this.propsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string otherprops {
        get {
            return this.otherpropsField;
        }
        set {
            this.otherpropsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string d {
        get {
            return this.dField;
        }
        set {
            this.dField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ol {
    
    private li[] liField;
    
    private string outputclassField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("li", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public li[] li {
        get {
            return this.liField;
        }
        set {
            this.liField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string outputclass {
        get {
            return this.outputclassField;
        }
        set {
            this.outputclassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class p {
    
    private i[] iField;
    
    private b[] bField;
    
    private foreign[] foreignField;
    
    private sup[] supField;
    
    private image imageField;
    
    private xref[] xrefField;
    
    private u[] uField;
    
    private sub[] subField;
    
    private fn[] fnField;
    
    private string outputclassField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("i", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public i[] i {
        get {
            return this.iField;
        }
        set {
            this.iField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("b", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public b[] b {
        get {
            return this.bField;
        }
        set {
            this.bField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("foreign", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public foreign[] foreign {
        get {
            return this.foreignField;
        }
        set {
            this.foreignField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public sup[] sup {
        get {
            return this.supField;
        }
        set {
            this.supField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public image image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("xref", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public xref[] xref {
        get {
            return this.xrefField;
        }
        set {
            this.xrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("u", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public u[] u {
        get {
            return this.uField;
        }
        set {
            this.uField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sub", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public sub[] sub {
        get {
            return this.subField;
        }
        set {
            this.subField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("fn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public fn[] fn {
        get {
            return this.fnField;
        }
        set {
            this.fnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string outputclass {
        get {
            return this.outputclassField;
        }
        set {
            this.outputclassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class foreign {
    
    private OLEObject oLEObjectField;
    
    private OLEImage oLEImageField;
    
    private mathML mathMLField;
    
    private image imageField;
    
    private string idField;
    
    private string heightField;
    
    private string widthField;
    
    private string widthdpiField;
    
    private string heightdpiField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public OLEObject OLEObject {
        get {
            return this.oLEObjectField;
        }
        set {
            this.oLEObjectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public OLEImage OLEImage {
        get {
            return this.oLEImageField;
        }
        set {
            this.oLEImageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public mathML mathML {
        get {
            return this.mathMLField;
        }
        set {
            this.mathMLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public image image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string widthdpi {
        get {
            return this.widthdpiField;
        }
        set {
            this.widthdpiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string heightdpi {
        get {
            return this.heightdpiField;
        }
        set {
            this.heightdpiField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class OLEObject {
    
    private string dxaOriginalField;
    
    private string dyaOriginalField;
    
    private string defaultStyleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dxaOriginal {
        get {
            return this.dxaOriginalField;
        }
        set {
            this.dxaOriginalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dyaOriginal {
        get {
            return this.dyaOriginalField;
        }
        set {
            this.dyaOriginalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defaultStyle {
        get {
            return this.defaultStyleField;
        }
        set {
            this.defaultStyleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class OLEImage {
    
    private string contenttypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("content-type")]
    public string contenttype {
        get {
            return this.contenttypeField;
        }
        set {
            this.contenttypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class mathML {
    
    private math mathField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public math math {
        get {
            return this.mathField;
        }
        set {
            this.mathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class math {
    
    private semantics semanticsField;
    
    private string displayField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public semantics semantics {
        get {
            return this.semanticsField;
        }
        set {
            this.semanticsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string display {
        get {
            return this.displayField;
        }
        set {
            this.displayField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class semantics {
    
    private mrow mrowField;
    
    private annotation annotationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public mrow mrow {
        get {
            return this.mrowField;
        }
        set {
            this.mrowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public annotation annotation {
        get {
            return this.annotationField;
        }
        set {
            this.annotationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class mrow {
    
    private mtable[] mtableField;
    
    private mfrac[] mfracField;
    
    private string[] mtextField;
    
    private mo[] moField;
    
    private mrow[] mrow1Field;
    
    private string[] miField;
    
    private string[] mnField;
    
    private msub[] msubField;
    
    private msup[] msupField;
    
    private mstyle[] mstyleField;
    
    private munderover[] munderoverField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mtable", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public mtable[] mtable {
        get {
            return this.mtableField;
        }
        set {
            this.mtableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mfrac", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public mfrac[] mfrac {
        get {
            return this.mfracField;
        }
        set {
            this.mfracField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mtext", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] mtext {
        get {
            return this.mtextField;
        }
        set {
            this.mtextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public mo[] mo {
        get {
            return this.moField;
        }
        set {
            this.moField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mrow", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public mrow[] mrow1 {
        get {
            return this.mrow1Field;
        }
        set {
            this.mrow1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mi", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] mi {
        get {
            return this.miField;
        }
        set {
            this.miField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] mn {
        get {
            return this.mnField;
        }
        set {
            this.mnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("msub", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public msub[] msub {
        get {
            return this.msubField;
        }
        set {
            this.msubField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("msup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public msup[] msup {
        get {
            return this.msupField;
        }
        set {
            this.msupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mstyle", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public mstyle[] mstyle {
        get {
            return this.mstyleField;
        }
        set {
            this.mstyleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("munderover", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public munderover[] munderover {
        get {
            return this.munderoverField;
        }
        set {
            this.munderoverField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class mtable {
    
    private mtr[] mtrField;
    
    private string columnalignField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mtr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public mtr[] mtr {
        get {
            return this.mtrField;
        }
        set {
            this.mtrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string columnalign {
        get {
            return this.columnalignField;
        }
        set {
            this.columnalignField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class mtr {
    
    private mtd[] mtdField;
    
    private string columnalignField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mtd", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public mtd[] mtd {
        get {
            return this.mtdField;
        }
        set {
            this.mtdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string columnalign {
        get {
            return this.columnalignField;
        }
        set {
            this.columnalignField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class mtd {
    
    private mrow mrowField;
    
    private string columnalignField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public mrow mrow {
        get {
            return this.mrowField;
        }
        set {
            this.mrowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string columnalign {
        get {
            return this.columnalignField;
        }
        set {
            this.columnalignField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class mfrac {
    
    private mrow[] mrowField;
    
    private string[] mtextField;
    
    private string[] mnField;
    
    private string miField;
    
    private string bevelledField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mrow", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public mrow[] mrow {
        get {
            return this.mrowField;
        }
        set {
            this.mrowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mtext", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] mtext {
        get {
            return this.mtextField;
        }
        set {
            this.mtextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] mn {
        get {
            return this.mnField;
        }
        set {
            this.mnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mi {
        get {
            return this.miField;
        }
        set {
            this.miField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bevelled {
        get {
            return this.bevelledField;
        }
        set {
            this.bevelledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class mo {
    
    private string stretchyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stretchy {
        get {
            return this.stretchyField;
        }
        set {
            this.stretchyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class msub {
    
    private mrow[] mrowField;
    
    private string[] mtextField;
    
    private string mnField;
    
    private string[] miField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mrow", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public mrow[] mrow {
        get {
            return this.mrowField;
        }
        set {
            this.mrowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mtext", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] mtext {
        get {
            return this.mtextField;
        }
        set {
            this.mtextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mn {
        get {
            return this.mnField;
        }
        set {
            this.mnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mi", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] mi {
        get {
            return this.miField;
        }
        set {
            this.miField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class msup {
    
    private mrow[] mrowField;
    
    private string mtextField;
    
    private string mnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mrow", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public mrow[] mrow {
        get {
            return this.mrowField;
        }
        set {
            this.mrowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mtext {
        get {
            return this.mtextField;
        }
        set {
            this.mtextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mn {
        get {
            return this.mnField;
        }
        set {
            this.mnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class mstyle {
    
    private mo moField;
    
    private mrow mrowField;
    
    private munderover munderoverField;
    
    private string[] miField;
    
    private string displaystyleField;
    
    private string mathsizeField;
    
    private string mathvariantField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public mo mo {
        get {
            return this.moField;
        }
        set {
            this.moField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public mrow mrow {
        get {
            return this.mrowField;
        }
        set {
            this.mrowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public munderover munderover {
        get {
            return this.munderoverField;
        }
        set {
            this.munderoverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mi", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] mi {
        get {
            return this.miField;
        }
        set {
            this.miField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displaystyle {
        get {
            return this.displaystyleField;
        }
        set {
            this.displaystyleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mathsize {
        get {
            return this.mathsizeField;
        }
        set {
            this.mathsizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mathvariant {
        get {
            return this.mathvariantField;
        }
        set {
            this.mathvariantField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class munderover {
    
    private mo moField;
    
    private mrow mrowField;
    
    private string mtextField;
    
    private mstyle mstyleField;
    
    private string miField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public mo mo {
        get {
            return this.moField;
        }
        set {
            this.moField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public mrow mrow {
        get {
            return this.mrowField;
        }
        set {
            this.mrowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mtext {
        get {
            return this.mtextField;
        }
        set {
            this.mtextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public mstyle mstyle {
        get {
            return this.mstyleField;
        }
        set {
            this.mstyleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mi {
        get {
            return this.miField;
        }
        set {
            this.miField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class annotation {
    
    private string encodingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string encoding {
        get {
            return this.encodingField;
        }
        set {
            this.encodingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class image {
    
    private string contenttypeField;
    
    private string hrefField;
    
    private string heightField;
    
    private string widthField;
    
    private string widthdpiField;
    
    private string heightdpiField;
    
    private string idField;
    
    private string altField;
    
    private string alignField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("content-type")]
    public string contenttype {
        get {
            return this.contenttypeField;
        }
        set {
            this.contenttypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string widthdpi {
        get {
            return this.widthdpiField;
        }
        set {
            this.widthdpiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string heightdpi {
        get {
            return this.heightdpiField;
        }
        set {
            this.heightdpiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string alt {
        get {
            return this.altField;
        }
        set {
            this.altField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string align {
        get {
            return this.alignField;
        }
        set {
            this.alignField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class xref {
    
    private string hrefField;
    
    private string formatField;
    
    private string idField;
    
    private string scopeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string href {
        get {
            return this.hrefField;
        }
        set {
            this.hrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string scope {
        get {
            return this.scopeField;
        }
        set {
            this.scopeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class fn {
    
    private string idField;
    
    private string calloutField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string callout {
        get {
            return this.calloutField;
        }
        set {
            this.calloutField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class fig {
    
    private image imageField;
    
    private title titleField;
    
    private string frameField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public image image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public title title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string frame {
        get {
            return this.frameField;
        }
        set {
            this.frameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class body {
    
    private p[] pField;
    
    private ol[] olField;
    
    private fig[] figField;
    
    private image[] imageField;
    
    private ul[] ulField;
    
    private note[] noteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("p", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public p[] p {
        get {
            return this.pField;
        }
        set {
            this.pField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ol", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ol[] ol {
        get {
            return this.olField;
        }
        set {
            this.olField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("fig", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public fig[] fig {
        get {
            return this.figField;
        }
        set {
            this.figField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("image", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public image[] image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ul", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ul[] ul {
        get {
            return this.ulField;
        }
        set {
            this.ulField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("note", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public note[] note {
        get {
            return this.noteField;
        }
        set {
            this.noteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class othermeta {
    
    private string nameField;
    
    private string contentField;
    
    private string propsField;
    
    private string baseField;
    
    private string revField;
    
    private string otherpropsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string props {
        get {
            return this.propsField;
        }
        set {
            this.propsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @base {
        get {
            return this.baseField;
        }
        set {
            this.baseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rev {
        get {
            return this.revField;
        }
        set {
            this.revField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string otherprops {
        get {
            return this.otherpropsField;
        }
        set {
            this.otherpropsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class prolog {
    
    private othermeta[] metadataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public othermeta[] metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class shortdesc {
    
    private i[] iField;
    
    private sub subField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("i", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public i[] i {
        get {
            return this.iField;
        }
        set {
            this.iField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public sub sub {
        get {
            return this.subField;
        }
        set {
            this.subField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}
