//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/PDFDoc.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/PDFDoc.xsd", IsNullable=false)]
public partial class PDFDoc {
    
    private PDFPage[] pDFPageField;
    
    private string pDFDocNameField;
    
    private string pDFDocPathField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PDFPage")]
    public PDFPage[] PDFPage {
        get {
            return this.pDFPageField;
        }
        set {
            this.pDFPageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PDFDocName {
        get {
            return this.pDFDocNameField;
        }
        set {
            this.pDFDocNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PDFDocPath {
        get {
            return this.pDFDocPathField;
        }
        set {
            this.pDFDocPathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/PDFDoc.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/PDFDoc.xsd", IsNullable=false)]
public partial class PDFPage {
    
    private PDFLine[] pDFLineField;
    
    private int pDFPageNumberField;
    
    private bool pDFPageNumberFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PDFLine")]
    public PDFLine[] PDFLine {
        get {
            return this.pDFLineField;
        }
        set {
            this.pDFLineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int PDFPageNumber {
        get {
            return this.pDFPageNumberField;
        }
        set {
            this.pDFPageNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PDFPageNumberSpecified {
        get {
            return this.pDFPageNumberFieldSpecified;
        }
        set {
            this.pDFPageNumberFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/PDFDoc.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/PDFDoc.xsd", IsNullable=false)]
public partial class PDFLine {
    
    private PDFToken[] pDFTokenField;
    
    private int pDFLineNumberField;
    
    private bool pDFLineNumberFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PDFToken")]
    public PDFToken[] PDFToken {
        get {
            return this.pDFTokenField;
        }
        set {
            this.pDFTokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int PDFLineNumber {
        get {
            return this.pDFLineNumberField;
        }
        set {
            this.pDFLineNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PDFLineNumberSpecified {
        get {
            return this.pDFLineNumberFieldSpecified;
        }
        set {
            this.pDFLineNumberFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/PDFDoc.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/PDFDoc.xsd", IsNullable=false)]
public partial class PDFToken {
    
    private int coordXField;
    
    private bool coordXFieldSpecified;
    
    private int coordYField;
    
    private bool coordYFieldSpecified;
    
    private string fontFamilyField;
    
    private string fontSizeField;
    
    private bool boldField;
    
    private bool boldFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int CoordX {
        get {
            return this.coordXField;
        }
        set {
            this.coordXField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CoordXSpecified {
        get {
            return this.coordXFieldSpecified;
        }
        set {
            this.coordXFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int CoordY {
        get {
            return this.coordYField;
        }
        set {
            this.coordYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CoordYSpecified {
        get {
            return this.coordYFieldSpecified;
        }
        set {
            this.coordYFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FontFamily {
        get {
            return this.fontFamilyField;
        }
        set {
            this.fontFamilyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FontSize {
        get {
            return this.fontSizeField;
        }
        set {
            this.fontSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Bold {
        get {
            return this.boldField;
        }
        set {
            this.boldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BoldSpecified {
        get {
            return this.boldFieldSpecified;
        }
        set {
            this.boldFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
