//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFX_P8_Image.Client.FFXImageServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FFXImageServices.IFFXImageService")]
    public interface IFFXImageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFFXImageService/GetTicketsList", ReplyAction="http://tempuri.org/IFFXImageService/GetTicketsListResponse")]
        System.Collections.ObjectModel.ObservableCollection<string> GetTicketsList(string sTicketNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFFXImageService/GetTicketsList", ReplyAction="http://tempuri.org/IFFXImageService/GetTicketsListResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<string>> GetTicketsListAsync(string sTicketNum);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFFXImageServiceChannel : FFX_P8_Image.Client.FFXImageServices.IFFXImageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FFXImageServiceClient : System.ServiceModel.ClientBase<FFX_P8_Image.Client.FFXImageServices.IFFXImageService>, FFX_P8_Image.Client.FFXImageServices.IFFXImageService {
        
        public FFXImageServiceClient() {
        }
        
        public FFXImageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FFXImageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FFXImageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FFXImageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> GetTicketsList(string sTicketNum) {
            return base.Channel.GetTicketsList(sTicketNum);
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<string>> GetTicketsListAsync(string sTicketNum) {
            return base.Channel.GetTicketsListAsync(sTicketNum);
        }
    }
}
