//------------------------------------------------------------------------------
/// <autogenerated>
///     This code was generated by a tool.
///     Runtime Version: 4.0.30319.18444
///
///     Changes to this file may cause incorrect behavior and will be lost if 
///     the code is regenerated.
/// </autogenerated>
//------------------------------------------------------------------------------

//@cc_on
//@set @debug(off)

import System.Xml.Serialization;

//
//This source code was auto-generated by xsd, Version=4.0.30319.33440.
//

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlRootAttribute("topic", Namespace="", IsNullable=false) 
class topicType {
    
    private var itemsField : System.Object[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("body", bodyType) System.Xml.Serialization.XmlElementAttribute("prolog", prologType) System.Xml.Serialization.XmlElementAttribute("shortdesc", shortdescType) System.Xml.Serialization.XmlElementAttribute("title", titleType) 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class bodyType {
    
    private var itemsField : System.Object[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("fig", figType) System.Xml.Serialization.XmlElementAttribute("image", System.String) System.Xml.Serialization.XmlElementAttribute("note", noteType) System.Xml.Serialization.XmlElementAttribute("ol", olType) System.Xml.Serialization.XmlElementAttribute("p", pType) System.Xml.Serialization.XmlElementAttribute("table", tableType) System.Xml.Serialization.XmlElementAttribute("ul", ulType) 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class figType {
    
    private var itemsField : System.Object[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("image", System.String) System.Xml.Serialization.XmlElementAttribute("title", titleType) 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class titleType {
    
    private var itemsField : System.Object[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("b", bType) System.Xml.Serialization.XmlElementAttribute("i", iType) System.Xml.Serialization.XmlElementAttribute("sub", subType) System.Xml.Serialization.XmlElementAttribute("sup", supType) System.Xml.Serialization.XmlElementAttribute("u", uType) 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class bType {
    
    private var itemsField : System.Object[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("i", iType) System.Xml.Serialization.XmlElementAttribute("sub", subType) System.Xml.Serialization.XmlElementAttribute("sup", supType) System.Xml.Serialization.XmlElementAttribute("u", uType) 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class iType {
    
    private var itemsField : System.Object[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("b", bType) System.Xml.Serialization.XmlElementAttribute("u", uType) 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class uType {
    
    private var itemsField : System.Object[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("b", bType) System.Xml.Serialization.XmlElementAttribute("i", iType) System.Xml.Serialization.XmlElementAttribute("sub", subType) System.Xml.Serialization.XmlElementAttribute("sup", supType) 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class subType {
    
    private var itemsField : System.Object[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("b", bType) System.Xml.Serialization.XmlElementAttribute("i", iType) 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class noteType {
    
    private var itemsField : uType[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("u") 
    function get Items() : uType[] {
        return this.itemsField;
    }
    public final function set Items(value : uType[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class ulType {
    
    private var itemsField : liType[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("li") 
    function get Items() : liType[] {
        return this.itemsField;
    }
    public final function set Items(value : liType[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class liType {
    
    private var itemsField : System.Object[];
    
    private var itemsElementNameField : ItemsChoiceType9[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("b", bType) System.Xml.Serialization.XmlElementAttribute("fig", figType) System.Xml.Serialization.XmlElementAttribute("fn", System.String) System.Xml.Serialization.XmlElementAttribute("foreign", foreignType) System.Xml.Serialization.XmlElementAttribute("i", iType) System.Xml.Serialization.XmlElementAttribute("image", System.String) System.Xml.Serialization.XmlElementAttribute("note", noteType) System.Xml.Serialization.XmlElementAttribute("ol", olType) System.Xml.Serialization.XmlElementAttribute("p", pType) System.Xml.Serialization.XmlElementAttribute("sub", subType) System.Xml.Serialization.XmlElementAttribute("sup", supType) System.Xml.Serialization.XmlElementAttribute("table", tableType) System.Xml.Serialization.XmlElementAttribute("u", uType) System.Xml.Serialization.XmlElementAttribute("ul", ulType) System.Xml.Serialization.XmlElementAttribute("xref", System.String) System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName") 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("ItemsElementName") System.Xml.Serialization.XmlIgnoreAttribute() 
    function get ItemsElementName() : ItemsChoiceType9[] {
        return this.itemsElementNameField;
    }
    public final function set ItemsElementName(value : ItemsChoiceType9[]) {
        this.itemsElementNameField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class foreignType {
    
    private var itemsField : System.Object[];
    
    private var itemsElementNameField : ItemsChoiceType7[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("OLEImage", System.String) System.Xml.Serialization.XmlElementAttribute("OLEObject", System.String) System.Xml.Serialization.XmlElementAttribute("image", System.String) System.Xml.Serialization.XmlElementAttribute("mathML", mathMLType) System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName") 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("ItemsElementName") System.Xml.Serialization.XmlIgnoreAttribute() 
    function get ItemsElementName() : ItemsChoiceType7[] {
        return this.itemsElementNameField;
    }
    public final function set ItemsElementName(value : ItemsChoiceType7[]) {
        this.itemsElementNameField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class mathMLType {
    
    private var itemsField : mathType[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("math") 
    function get Items() : mathType[] {
        return this.itemsField;
    }
    public final function set Items(value : mathType[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class mathType {
    
    private var itemsField : semanticsType[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("semantics") 
    function get Items() : semanticsType[] {
        return this.itemsField;
    }
    public final function set Items(value : semanticsType[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class semanticsType {
    
    private var itemsField : System.Object[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("annotation", System.String) System.Xml.Serialization.XmlElementAttribute("mrow", mrowType) System.Xml.Serialization.XmlElementAttribute("mtable", mtableType) 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class mrowType {
    
    private var itemsField : System.Object[];
    
    private var itemsElementNameField : ItemsChoiceType6[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("mfrac", mfracType) System.Xml.Serialization.XmlElementAttribute("mi", System.String) System.Xml.Serialization.XmlElementAttribute("mn", System.String) System.Xml.Serialization.XmlElementAttribute("mo", System.String) System.Xml.Serialization.XmlElementAttribute("mrow", mrowType) System.Xml.Serialization.XmlElementAttribute("mstyle", mstyleType) System.Xml.Serialization.XmlElementAttribute("msub", msubType) System.Xml.Serialization.XmlElementAttribute("msup", msupType) System.Xml.Serialization.XmlElementAttribute("mtable", mtableType) System.Xml.Serialization.XmlElementAttribute("mtext", System.String) System.Xml.Serialization.XmlElementAttribute("munderover", munderoverType) System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName") 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("ItemsElementName") System.Xml.Serialization.XmlIgnoreAttribute() 
    function get ItemsElementName() : ItemsChoiceType6[] {
        return this.itemsElementNameField;
    }
    public final function set ItemsElementName(value : ItemsChoiceType6[]) {
        this.itemsElementNameField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class mfracType {
    
    private var itemsField : System.Object[];
    
    private var itemsElementNameField : ItemsChoiceType[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("mi", System.String) System.Xml.Serialization.XmlElementAttribute("mn", System.String) System.Xml.Serialization.XmlElementAttribute("mrow", mrowType) System.Xml.Serialization.XmlElementAttribute("mtext", System.String) System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName") 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("ItemsElementName") System.Xml.Serialization.XmlIgnoreAttribute() 
    function get ItemsElementName() : ItemsChoiceType[] {
        return this.itemsElementNameField;
    }
    public final function set ItemsElementName(value : ItemsChoiceType[]) {
        this.itemsElementNameField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false) 
enum ItemsChoiceType {
    
    ///<remarks/>
    mi,
    
    ///<remarks/>
    mn,
    
    ///<remarks/>
    mrow,
    
    ///<remarks/>
    mtext,
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class mstyleType {
    
    private var itemsField : System.Object[];
    
    private var itemsElementNameField : ItemsChoiceType5[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("mi", System.String) System.Xml.Serialization.XmlElementAttribute("mo", System.String) System.Xml.Serialization.XmlElementAttribute("mrow", mrowType) System.Xml.Serialization.XmlElementAttribute("munderover", munderoverType) System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName") 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("ItemsElementName") System.Xml.Serialization.XmlIgnoreAttribute() 
    function get ItemsElementName() : ItemsChoiceType5[] {
        return this.itemsElementNameField;
    }
    public final function set ItemsElementName(value : ItemsChoiceType5[]) {
        this.itemsElementNameField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class munderoverType {
    
    private var itemsField : System.Object[];
    
    private var itemsElementNameField : ItemsChoiceType4[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("mi", System.String) System.Xml.Serialization.XmlElementAttribute("mo", System.String) System.Xml.Serialization.XmlElementAttribute("mrow", mrowType) System.Xml.Serialization.XmlElementAttribute("mstyle", mstyleType) System.Xml.Serialization.XmlElementAttribute("mtext", System.String) System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName") 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("ItemsElementName") System.Xml.Serialization.XmlIgnoreAttribute() 
    function get ItemsElementName() : ItemsChoiceType4[] {
        return this.itemsElementNameField;
    }
    public final function set ItemsElementName(value : ItemsChoiceType4[]) {
        this.itemsElementNameField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false) 
enum ItemsChoiceType4 {
    
    ///<remarks/>
    mi,
    
    ///<remarks/>
    mo,
    
    ///<remarks/>
    mrow,
    
    ///<remarks/>
    mstyle,
    
    ///<remarks/>
    mtext,
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false) 
enum ItemsChoiceType5 {
    
    ///<remarks/>
    mi,
    
    ///<remarks/>
    mo,
    
    ///<remarks/>
    mrow,
    
    ///<remarks/>
    munderover,
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class msubType {
    
    private var itemsField : System.Object[];
    
    private var itemsElementNameField : ItemsChoiceType2[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("mi", System.String) System.Xml.Serialization.XmlElementAttribute("mn", System.String) System.Xml.Serialization.XmlElementAttribute("mrow", mrowType) System.Xml.Serialization.XmlElementAttribute("mtext", System.String) System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName") 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("ItemsElementName") System.Xml.Serialization.XmlIgnoreAttribute() 
    function get ItemsElementName() : ItemsChoiceType2[] {
        return this.itemsElementNameField;
    }
    public final function set ItemsElementName(value : ItemsChoiceType2[]) {
        this.itemsElementNameField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false) 
enum ItemsChoiceType2 {
    
    ///<remarks/>
    mi,
    
    ///<remarks/>
    mn,
    
    ///<remarks/>
    mrow,
    
    ///<remarks/>
    mtext,
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class msupType {
    
    private var itemsField : System.Object[];
    
    private var itemsElementNameField : ItemsChoiceType3[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("mn", System.String) System.Xml.Serialization.XmlElementAttribute("mrow", mrowType) System.Xml.Serialization.XmlElementAttribute("mtext", System.String) System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName") 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("ItemsElementName") System.Xml.Serialization.XmlIgnoreAttribute() 
    function get ItemsElementName() : ItemsChoiceType3[] {
        return this.itemsElementNameField;
    }
    public final function set ItemsElementName(value : ItemsChoiceType3[]) {
        this.itemsElementNameField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false) 
enum ItemsChoiceType3 {
    
    ///<remarks/>
    mn,
    
    ///<remarks/>
    mrow,
    
    ///<remarks/>
    mtext,
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class mtableType {
    
    private var itemsField : mtrType[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("mtr") 
    function get Items() : mtrType[] {
        return this.itemsField;
    }
    public final function set Items(value : mtrType[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class mtrType {
    
    private var itemsField : mtdType[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("mtd") 
    function get Items() : mtdType[] {
        return this.itemsField;
    }
    public final function set Items(value : mtdType[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class mtdType {
    
    private var itemsField : System.Object[];
    
    private var itemsElementNameField : ItemsChoiceType1[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("mfrac", mfracType) System.Xml.Serialization.XmlElementAttribute("mi", System.String) System.Xml.Serialization.XmlElementAttribute("mn", System.String) System.Xml.Serialization.XmlElementAttribute("mo", System.String) System.Xml.Serialization.XmlElementAttribute("mrow", mrowType) System.Xml.Serialization.XmlElementAttribute("mtext", System.String) System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName") 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("ItemsElementName") System.Xml.Serialization.XmlIgnoreAttribute() 
    function get ItemsElementName() : ItemsChoiceType1[] {
        return this.itemsElementNameField;
    }
    public final function set ItemsElementName(value : ItemsChoiceType1[]) {
        this.itemsElementNameField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false) 
enum ItemsChoiceType1 {
    
    ///<remarks/>
    mfrac,
    
    ///<remarks/>
    mi,
    
    ///<remarks/>
    mn,
    
    ///<remarks/>
    mo,
    
    ///<remarks/>
    mrow,
    
    ///<remarks/>
    mtext,
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false) 
enum ItemsChoiceType6 {
    
    ///<remarks/>
    mfrac,
    
    ///<remarks/>
    mi,
    
    ///<remarks/>
    mn,
    
    ///<remarks/>
    mo,
    
    ///<remarks/>
    mrow,
    
    ///<remarks/>
    mstyle,
    
    ///<remarks/>
    msub,
    
    ///<remarks/>
    msup,
    
    ///<remarks/>
    mtable,
    
    ///<remarks/>
    mtext,
    
    ///<remarks/>
    munderover,
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false) 
enum ItemsChoiceType7 {
    
    ///<remarks/>
    OLEImage,
    
    ///<remarks/>
    OLEObject,
    
    ///<remarks/>
    image,
    
    ///<remarks/>
    mathML,
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class olType {
    
    private var itemsField : liType[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("li") 
    function get Items() : liType[] {
        return this.itemsField;
    }
    public final function set Items(value : liType[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class pType {
    
    private var itemsField : System.Object[];
    
    private var itemsElementNameField : ItemsChoiceType8[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("b", bType) System.Xml.Serialization.XmlElementAttribute("fn", System.String) System.Xml.Serialization.XmlElementAttribute("foreign", foreignType) System.Xml.Serialization.XmlElementAttribute("i", iType) System.Xml.Serialization.XmlElementAttribute("image", System.String) System.Xml.Serialization.XmlElementAttribute("sub", subType) System.Xml.Serialization.XmlElementAttribute("sup", supType) System.Xml.Serialization.XmlElementAttribute("tn", System.String) System.Xml.Serialization.XmlElementAttribute("u", uType) System.Xml.Serialization.XmlElementAttribute("xref", System.String) System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName") 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("ItemsElementName") System.Xml.Serialization.XmlIgnoreAttribute() 
    function get ItemsElementName() : ItemsChoiceType8[] {
        return this.itemsElementNameField;
    }
    public final function set ItemsElementName(value : ItemsChoiceType8[]) {
        this.itemsElementNameField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class supType {
    
    private var itemsField : System.Object[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("b", bType) System.Xml.Serialization.XmlElementAttribute("i", iType) 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false) 
enum ItemsChoiceType8 {
    
    ///<remarks/>
    b,
    
    ///<remarks/>
    fn,
    
    ///<remarks/>
    foreign,
    
    ///<remarks/>
    i,
    
    ///<remarks/>
    image,
    
    ///<remarks/>
    sub,
    
    ///<remarks/>
    sup,
    
    ///<remarks/>
    tn,
    
    ///<remarks/>
    u,
    
    ///<remarks/>
    xref,
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class tableType {
    
    private var itemsField : System.Object[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("desc", descType) System.Xml.Serialization.XmlElementAttribute("tgroup", tgroupType) System.Xml.Serialization.XmlElementAttribute("title", titleType) 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class descType {
    
    private var itemsField : System.Object[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("b", bType) System.Xml.Serialization.XmlElementAttribute("sup", supType) 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class tgroupType {
    
    private var itemsField : System.Object[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("colspec", System.String) System.Xml.Serialization.XmlElementAttribute("tbody", tbodyType) System.Xml.Serialization.XmlElementAttribute("thead", theadType) 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class tbodyType {
    
    private var itemsField : rowType[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("row") 
    function get Items() : rowType[] {
        return this.itemsField;
    }
    public final function set Items(value : rowType[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class rowType {
    
    private var itemsField : entryType[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("entry") 
    function get Items() : entryType[] {
        return this.itemsField;
    }
    public final function set Items(value : entryType[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class entryType {
    
    private var itemsField : System.Object[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("foreign", foreignType) System.Xml.Serialization.XmlElementAttribute("image", System.String) System.Xml.Serialization.XmlElementAttribute("p", pType) 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class theadType {
    
    private var itemsField : rowType[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("row") 
    function get Items() : rowType[] {
        return this.itemsField;
    }
    public final function set Items(value : rowType[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false) 
enum ItemsChoiceType9 {
    
    ///<remarks/>
    b,
    
    ///<remarks/>
    fig,
    
    ///<remarks/>
    fn,
    
    ///<remarks/>
    foreign,
    
    ///<remarks/>
    i,
    
    ///<remarks/>
    image,
    
    ///<remarks/>
    note,
    
    ///<remarks/>
    ol,
    
    ///<remarks/>
    p,
    
    ///<remarks/>
    sub,
    
    ///<remarks/>
    sup,
    
    ///<remarks/>
    table,
    
    ///<remarks/>
    u,
    
    ///<remarks/>
    ul,
    
    ///<remarks/>
    xref,
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class metadataType {
    
    private var itemsField : System.String[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("othermeta") 
    function get Items() : System.String[] {
        return this.itemsField;
    }
    public final function set Items(value : System.String[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class prologType {
    
    private var itemsField : metadataType[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("metadata") 
    function get Items() : metadataType[] {
        return this.itemsField;
    }
    public final function set Items(value : metadataType[]) {
        this.itemsField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") 
class shortdescType {
    
    private var itemsField : System.Object[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("i", iType) System.Xml.Serialization.XmlElementAttribute("sub", subType) 
    function get Items() : System.Object[] {
        return this.itemsField;
    }
    public final function set Items(value : System.Object[]) {
        this.itemsField = value;
    }
}
