//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("topic", Namespace="", IsNullable=false)]
public partial class topicType {
    
    private string titleField;
    
    private shortdescType shortdescField;
    
    private prologType prologField;
    
    private bodyType bodyField;
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public shortdescType shortdesc {
        get {
            return this.shortdescField;
        }
        set {
            this.shortdescField = value;
        }
    }
    
    /// <remarks/>
    public prologType prolog {
        get {
            return this.prologField;
        }
        set {
            this.prologField = value;
        }
    }
    
    /// <remarks/>
    public bodyType body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class shortdescType {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("i", typeof(iType))]
    [System.Xml.Serialization.XmlElementAttribute("sub", typeof(subType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class iType {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("b", typeof(bType))]
    [System.Xml.Serialization.XmlElementAttribute("u", typeof(uType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class bType {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("i", typeof(iType))]
    [System.Xml.Serialization.XmlElementAttribute("sub", typeof(subType))]
    [System.Xml.Serialization.XmlElementAttribute("sup", typeof(supType))]
    [System.Xml.Serialization.XmlElementAttribute("u", typeof(uType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class subType {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("b", typeof(bType))]
    [System.Xml.Serialization.XmlElementAttribute("i", typeof(iType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class noteType {
    
    private uType[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("u")]
    public uType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class uType {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("b", typeof(bType))]
    [System.Xml.Serialization.XmlElementAttribute("i", typeof(iType))]
    [System.Xml.Serialization.XmlElementAttribute("sub", typeof(subType))]
    [System.Xml.Serialization.XmlElementAttribute("sup", typeof(supType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class supType {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("b", typeof(bType))]
    [System.Xml.Serialization.XmlElementAttribute("i", typeof(iType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ulType {
    
    private liType[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("li")]
    public liType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class liType {
    
    private object[] itemsField;
    
    private ItemsChoiceType9[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("b", typeof(bType))]
    [System.Xml.Serialization.XmlElementAttribute("fig", typeof(figType))]
    [System.Xml.Serialization.XmlElementAttribute("fn", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("foreign", typeof(foreignType))]
    [System.Xml.Serialization.XmlElementAttribute("i", typeof(iType))]
    [System.Xml.Serialization.XmlElementAttribute("image", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("note", typeof(noteType))]
    [System.Xml.Serialization.XmlElementAttribute("ol", typeof(olType))]
    [System.Xml.Serialization.XmlElementAttribute("p", typeof(pType))]
    [System.Xml.Serialization.XmlElementAttribute("sub", typeof(subType))]
    [System.Xml.Serialization.XmlElementAttribute("sup", typeof(supType))]
    [System.Xml.Serialization.XmlElementAttribute("table", typeof(tableType))]
    [System.Xml.Serialization.XmlElementAttribute("u", typeof(uType))]
    [System.Xml.Serialization.XmlElementAttribute("ul", typeof(ulType))]
    [System.Xml.Serialization.XmlElementAttribute("xref", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType9[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class figType {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("image", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("title", typeof(titleType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class titleType {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("b", typeof(bType))]
    [System.Xml.Serialization.XmlElementAttribute("i", typeof(iType))]
    [System.Xml.Serialization.XmlElementAttribute("sub", typeof(subType))]
    [System.Xml.Serialization.XmlElementAttribute("sup", typeof(supType))]
    [System.Xml.Serialization.XmlElementAttribute("u", typeof(uType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class foreignType {
    
    private object[] itemsField;
    
    private ItemsChoiceType7[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OLEImage", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("OLEObject", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("image", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("mathML", typeof(mathMLType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType7[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class mathMLType {
    
    private mathType[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("math")]
    public mathType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class mathType {
    
    private semanticsType[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("semantics")]
    public semanticsType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class semanticsType {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("annotation", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("mrow", typeof(mrowType))]
    [System.Xml.Serialization.XmlElementAttribute("mtable", typeof(mtableType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class mrowType {
    
    private object[] itemsField;
    
    private ItemsChoiceType6[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mfrac", typeof(mfracType))]
    [System.Xml.Serialization.XmlElementAttribute("mi", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("mn", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("mo", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("mrow", typeof(mrowType))]
    [System.Xml.Serialization.XmlElementAttribute("mstyle", typeof(mstyleType))]
    [System.Xml.Serialization.XmlElementAttribute("msub", typeof(msubType))]
    [System.Xml.Serialization.XmlElementAttribute("msup", typeof(msupType))]
    [System.Xml.Serialization.XmlElementAttribute("mtable", typeof(mtableType))]
    [System.Xml.Serialization.XmlElementAttribute("mtext", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("munderover", typeof(munderoverType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType6[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class mfracType {
    
    private object[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mi", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("mn", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("mrow", typeof(mrowType))]
    [System.Xml.Serialization.XmlElementAttribute("mtext", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    mi,
    
    /// <remarks/>
    mn,
    
    /// <remarks/>
    mrow,
    
    /// <remarks/>
    mtext,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class mstyleType {
    
    private object[] itemsField;
    
    private ItemsChoiceType5[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mi", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("mo", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("mrow", typeof(mrowType))]
    [System.Xml.Serialization.XmlElementAttribute("munderover", typeof(munderoverType))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType5[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class munderoverType {
    
    private object[] itemsField;
    
    private ItemsChoiceType4[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mi", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("mo", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("mrow", typeof(mrowType))]
    [System.Xml.Serialization.XmlElementAttribute("mstyle", typeof(mstyleType))]
    [System.Xml.Serialization.XmlElementAttribute("mtext", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType4[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType4 {
    
    /// <remarks/>
    mi,
    
    /// <remarks/>
    mo,
    
    /// <remarks/>
    mrow,
    
    /// <remarks/>
    mstyle,
    
    /// <remarks/>
    mtext,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType5 {
    
    /// <remarks/>
    mi,
    
    /// <remarks/>
    mo,
    
    /// <remarks/>
    mrow,
    
    /// <remarks/>
    munderover,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class msubType {
    
    private object[] itemsField;
    
    private ItemsChoiceType2[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mi", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("mn", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("mrow", typeof(mrowType))]
    [System.Xml.Serialization.XmlElementAttribute("mtext", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType2[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType2 {
    
    /// <remarks/>
    mi,
    
    /// <remarks/>
    mn,
    
    /// <remarks/>
    mrow,
    
    /// <remarks/>
    mtext,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class msupType {
    
    private object[] itemsField;
    
    private ItemsChoiceType3[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mn", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("mrow", typeof(mrowType))]
    [System.Xml.Serialization.XmlElementAttribute("mtext", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType3[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType3 {
    
    /// <remarks/>
    mn,
    
    /// <remarks/>
    mrow,
    
    /// <remarks/>
    mtext,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class mtableType {
    
    private mtrType[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mtr")]
    public mtrType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class mtrType {
    
    private mtdType[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mtd")]
    public mtdType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class mtdType {
    
    private object[] itemsField;
    
    private ItemsChoiceType1[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mfrac", typeof(mfracType))]
    [System.Xml.Serialization.XmlElementAttribute("mi", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("mn", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("mo", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("mrow", typeof(mrowType))]
    [System.Xml.Serialization.XmlElementAttribute("mtext", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType1[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType1 {
    
    /// <remarks/>
    mfrac,
    
    /// <remarks/>
    mi,
    
    /// <remarks/>
    mn,
    
    /// <remarks/>
    mo,
    
    /// <remarks/>
    mrow,
    
    /// <remarks/>
    mtext,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType6 {
    
    /// <remarks/>
    mfrac,
    
    /// <remarks/>
    mi,
    
    /// <remarks/>
    mn,
    
    /// <remarks/>
    mo,
    
    /// <remarks/>
    mrow,
    
    /// <remarks/>
    mstyle,
    
    /// <remarks/>
    msub,
    
    /// <remarks/>
    msup,
    
    /// <remarks/>
    mtable,
    
    /// <remarks/>
    mtext,
    
    /// <remarks/>
    munderover,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType7 {
    
    /// <remarks/>
    OLEImage,
    
    /// <remarks/>
    OLEObject,
    
    /// <remarks/>
    image,
    
    /// <remarks/>
    mathML,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class olType {
    
    private liType[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("li")]
    public liType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class pType {
    
    private object[] itemsField;
    
    private ItemsChoiceType8[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("b", typeof(bType))]
    [System.Xml.Serialization.XmlElementAttribute("fn", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("foreign", typeof(foreignType))]
    [System.Xml.Serialization.XmlElementAttribute("i", typeof(iType))]
    [System.Xml.Serialization.XmlElementAttribute("image", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("sub", typeof(subType))]
    [System.Xml.Serialization.XmlElementAttribute("sup", typeof(supType))]
    [System.Xml.Serialization.XmlElementAttribute("tn", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("u", typeof(uType))]
    [System.Xml.Serialization.XmlElementAttribute("xref", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType8[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType8 {
    
    /// <remarks/>
    b,
    
    /// <remarks/>
    fn,
    
    /// <remarks/>
    foreign,
    
    /// <remarks/>
    i,
    
    /// <remarks/>
    image,
    
    /// <remarks/>
    sub,
    
    /// <remarks/>
    sup,
    
    /// <remarks/>
    tn,
    
    /// <remarks/>
    u,
    
    /// <remarks/>
    xref,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class tableType {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("desc", typeof(descType))]
    [System.Xml.Serialization.XmlElementAttribute("tgroup", typeof(tgroupType))]
    [System.Xml.Serialization.XmlElementAttribute("title", typeof(titleType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class descType {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("b", typeof(bType))]
    [System.Xml.Serialization.XmlElementAttribute("sup", typeof(supType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class tgroupType {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("colspec", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("tbody", typeof(tbodyType))]
    [System.Xml.Serialization.XmlElementAttribute("thead", typeof(theadType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class tbodyType {
    
    private rowType[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("row")]
    public rowType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class rowType {
    
    private entryType[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("entry")]
    public entryType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class entryType {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("foreign", typeof(foreignType))]
    [System.Xml.Serialization.XmlElementAttribute("image", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("p", typeof(pType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class theadType {
    
    private rowType[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("row")]
    public rowType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType9 {
    
    /// <remarks/>
    b,
    
    /// <remarks/>
    fig,
    
    /// <remarks/>
    fn,
    
    /// <remarks/>
    foreign,
    
    /// <remarks/>
    i,
    
    /// <remarks/>
    image,
    
    /// <remarks/>
    note,
    
    /// <remarks/>
    ol,
    
    /// <remarks/>
    p,
    
    /// <remarks/>
    sub,
    
    /// <remarks/>
    sup,
    
    /// <remarks/>
    table,
    
    /// <remarks/>
    u,
    
    /// <remarks/>
    ul,
    
    /// <remarks/>
    xref,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class bodyType {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("fig", typeof(figType))]
    [System.Xml.Serialization.XmlElementAttribute("image", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("note", typeof(noteType))]
    [System.Xml.Serialization.XmlElementAttribute("ol", typeof(olType))]
    [System.Xml.Serialization.XmlElementAttribute("p", typeof(pType))]
    [System.Xml.Serialization.XmlElementAttribute("table", typeof(tableType))]
    [System.Xml.Serialization.XmlElementAttribute("ul", typeof(ulType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class metadataType {
    
    private string[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("othermeta")]
    public string[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class prologType {
    
    private metadataType[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("metadata")]
    public metadataType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
